/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 路由健康檢查 */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/surveys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查詢所有問卷 */
        get: operations["SurveysController_findAll"];
        put?: never;
        /** 建立問卷（一律是 DRAFT） */
        post: operations["SurveysController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/surveys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查詢單一問卷 */
        get: operations["SurveysController_findOne"];
        put?: never;
        post?: never;
        /** 刪除問卷（擁有者或管理員；已有填答則不能刪） */
        delete: operations["SurveysController_remove"];
        options?: never;
        head?: never;
        /** 編輯問卷 */
        patch: operations["SurveysController_update"];
        trace?: never;
    };
    "/surveys/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 公開問卷（至少要有一題） */
        patch: operations["SurveysController_publish"];
        trace?: never;
    };
    "/surveys/{id}/unpublish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 不公開問卷 */
        patch: operations["SurveysController_unpublish"];
        trace?: never;
    };
    "/surveys/{surveyId}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查詢問卷所有題目 */
        get: operations["SurveysQuestionsController_findAll"];
        /** 整份取代問卷的題目（順序即陣列順序，只有 DRAFT 能改） */
        put: operations["SurveysQuestionsController_replace"];
        /** 建立題目 */
        post: operations["SurveysQuestionsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/questions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 刪除題目 */
        delete: operations["QuestionsController_remove"];
        options?: never;
        head?: never;
        /** 編輯題目 */
        patch: operations["QuestionsController_update"];
        trace?: never;
    };
    "/responses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查詢填寫 */
        get: operations["ResponsesController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/surveys/{surveyId}/responses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查詢所有填寫 */
        get: operations["SurveyResponsesController_findAll"];
        put?: never;
        /** 送出填寫 */
        post: operations["SurveyResponsesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/surveys/{surveyId}/responses/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查詢填答摘要（每題的分佈，不分頁） */
        get: operations["SurveyResponsesController_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用戶註冊 */
        post: operations["AuthController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用戶登入 */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查詢用戶資訊 */
        get: operations["AuthController_findMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        FieldErrorEntity: {
            /**
             * @description 出錯的欄位路徑；巢狀時是完整路徑
             * @example answers.0.questionId
             */
            field: string;
            /**
             * @description 違反的規則名。驗證失敗時是 class-validator 的裝飾器名，唯一衝突時是 unique
             * @example minLength
             */
            rule: string;
        };
        ErrorBodyEntity: {
            /**
             * @description 錯誤代碼，前端用它分支處理（不要解析 message）
             * @example NOT_FOUND
             * @enum {string}
             */
            code: "BAD_REQUEST" | "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "VALIDATION_FAILED" | "INTERNAL_ERROR";
            /**
             * @description 給人看的錯誤訊息，內容可能隨版本變動
             * @example 問卷不存在
             */
            message: string;
            /** @description 出錯的欄位清單。驗證失敗（400）與唯一衝突（409）會有，其餘錯誤沒有 */
            fields?: components["schemas"]["FieldErrorEntity"][];
        };
        ErrorResponseEntity: {
            /** @description 錯誤內容 */
            error: components["schemas"]["ErrorBodyEntity"];
        };
        QuestionEntity: {
            /**
             * @description 題目 id（cuid）
             * @example clx1a2b3c0000abcd1234efgh
             */
            id: string;
            /**
             * @description 問卷 id（cuid）
             * @example clx1a2b3c0000abcd1234efgh
             */
            surveyId: string;
            /**
             * @description 題目
             * @example 題目一
             */
            title: string;
            /**
             * @description 類型
             * @example TEXT
             * @enum {string}
             */
            type: "TEXT" | "SINGLE_CHOICE";
            /** @description 題號 */
            order: number;
            /** @description 選項 */
            options: string[];
        };
        SurveyListItemEntity: {
            /**
             * @description 問卷 id（cuid）
             * @example clx1a2b3c0000abcd1234efgh
             */
            id: string;
            /**
             * @description 問卷標題
             * @example 員工滿意度調查
             */
            title: string;
            /**
             * @description 問卷狀態
             * @example DRAFT
             * @enum {string}
             */
            status: "DRAFT" | "PUBLISHED";
            /**
             * Format: date-time
             * @description 建立時間
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description 最後更新時間
             */
            updatedAt: string;
            /** @description 題目清單，只有 ?includeQuestions=true 時才會出現 */
            questions?: components["schemas"]["QuestionEntity"][];
            /** @description 建立者的 User id，尚未有值時為 null */
            ownerId: string | null;
            /**
             * @description 這份問卷有幾題
             * @example 5
             */
            questionCount: number;
            /**
             * @description 這份問卷被填寫多少次
             * @example 10
             */
            responseCount: number;
        };
        PaginationMetaEntity: {
            /**
             * @description 目前第幾頁（從 1 開始）
             * @example 1
             */
            page: number;
            /**
             * @description 每頁筆數
             * @example 10
             */
            pageSize: number;
            /**
             * @description 符合條件的總筆數（不是這一頁的筆數）
             * @example 42
             */
            total: number;
            /**
             * @description 總頁數
             * @example 5
             */
            totalPages: number;
        };
        PaginatedSurveysEntity: {
            /** @description 回傳資料 */
            data: components["schemas"]["SurveyListItemEntity"][];
            /** @description 統計資訊 */
            meta: components["schemas"]["PaginationMetaEntity"];
        };
        SurveyEntity: {
            /**
             * @description 問卷 id（cuid）
             * @example clx1a2b3c0000abcd1234efgh
             */
            id: string;
            /**
             * @description 問卷標題
             * @example 員工滿意度調查
             */
            title: string;
            /**
             * @description 問卷狀態
             * @example DRAFT
             * @enum {string}
             */
            status: "DRAFT" | "PUBLISHED";
            /**
             * Format: date-time
             * @description 建立時間
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description 最後更新時間
             */
            updatedAt: string;
            /** @description 題目清單，只有 ?includeQuestions=true 時才會出現 */
            questions?: components["schemas"]["QuestionEntity"][];
            /** @description 建立者的 User id，尚未有值時為 null */
            ownerId: string | null;
        };
        CreateQuestionDto: {
            /**
             * @description 題目標題
             * @example 題目
             */
            title: string;
            /**
             * @description 類型
             * @enum {string}
             */
            type: "TEXT" | "SINGLE_CHOICE";
            /** @description 選項。SINGLE_CHOICE 至少兩個；TEXT 送空陣列 */
            options: string[];
        };
        CreateSurveyDto: {
            /**
             * @description 問卷標題
             * @example 員工滿意度調查
             */
            title: string;
            /** @description 一併建立的題目。順序就是陣列的順序；不給就是一份空草稿 */
            questions?: components["schemas"]["CreateQuestionDto"][];
        };
        UpdateSurveyDto: {
            /**
             * @description 問卷標題
             * @example 員工滿意度調查
             */
            title?: string;
            /** @description 一併建立的題目。順序就是陣列的順序；不給就是一份空草稿 */
            questions?: components["schemas"]["CreateQuestionDto"][];
        };
        ReplaceQuestionsDto: {
            /** @description 這份問卷取代後的完整題目清單。**順序就是陣列的順序**；送 [] 代表清空所有題目 */
            questions: components["schemas"]["CreateQuestionDto"][];
        };
        UpdateQuestionDto: {
            /**
             * @description 題目標題
             * @example 題目
             */
            title?: string;
            /**
             * @description 類型
             * @enum {string}
             */
            type?: "TEXT" | "SINGLE_CHOICE";
            /** @description 選項。SINGLE_CHOICE 至少兩個；TEXT 送空陣列 */
            options?: string[];
        };
        AnswerEntity: {
            /**
             * @description 答案 id（cuid）
             * @example clx1a2b3c0000abcd1234efgh
             */
            id: string;
            /**
             * @description 題目 id（cuid）
             * @example clx1a2b3c0000abcd1234efgh
             */
            questionId: string;
            /**
             * @description 填寫 id（cuid）
             * @example clx1a2b3c0000abcd1234efgh
             */
            responseId: string;
            /**
             * @description 內容
             * @example 回答內容
             */
            content: string;
            /** @description 這則答案對應的題目（GET /responses/:id 會一併帶回） */
            question: components["schemas"]["QuestionEntity"];
        };
        ResponseDetailEntity: {
            /**
             * @description 填寫 id（cuid）
             * @example clx1a2b3c0000abcd1234efgh
             */
            id: string;
            /**
             * @description 問卷 id（cuid）
             * @example clx1a2b3c0000abcd1234efgh
             */
            surveyId: string;
            /**
             * Format: date-time
             * @description 建立時間
             */
            createdAt: string;
            /** @description 回答 */
            answers: components["schemas"]["AnswerEntity"][];
        };
        AnswerDto: {
            /** @description 題目ID */
            questionId: string;
            /** @description 回答內容 */
            content: string;
        };
        CreateResponseDto: {
            /** @description 回答 */
            answers: components["schemas"]["AnswerDto"][];
        };
        ResponseEntity: {
            /**
             * @description 填寫 id（cuid）
             * @example clx1a2b3c0000abcd1234efgh
             */
            id: string;
            /**
             * @description 問卷 id（cuid）
             * @example clx1a2b3c0000abcd1234efgh
             */
            surveyId: string;
            /**
             * Format: date-time
             * @description 建立時間
             */
            createdAt: string;
        };
        PaginatedResponsesEntity: {
            /** @description 回傳資料 */
            data: components["schemas"]["ResponseEntity"][];
            /** @description 統計資訊 */
            meta: components["schemas"]["PaginationMetaEntity"];
        };
        OptionSummaryEntity: {
            /**
             * @description 選項的文字
             * @example 滿意
             */
            option: string;
            /**
             * @description 這個選項被選了幾次
             * @example 18
             */
            count: number;
        };
        QuestionSummaryEntity: {
            /**
             * @description 題目 id（cuid）
             * @example clx1a2b3c0000abcd1234efgh
             */
            questionId: string;
            /**
             * @description 題目
             * @example 整體滿意度
             */
            title: string;
            /**
             * @description 題目類型
             * @example SINGLE_CHOICE
             * @enum {string}
             */
            type: "TEXT" | "SINGLE_CHOICE";
            /**
             * @description 這題排第幾（從 0 開始）
             * @example 0
             */
            order: number;
            /**
             * @description 這一題實際收到幾筆答案
             * @example 27
             */
            answerCount: number;
            /** @description 每個選項各拿到幾票，**只有 SINGLE_CHOICE 才有**。以題目的 options 為基準，所以沒有人選的選項也會出現（count 是 0） */
            options?: components["schemas"]["OptionSummaryEntity"][];
            /** @description 最近幾筆回答的原文，**只有 TEXT 才有**，最新的排在前面。這是抽樣不是全部 —— 要看全部請用 GET /surveys/:surveyId/responses */
            samples?: string[];
        };
        SurveySummaryEntity: {
            /**
             * @description 問卷 id（cuid）
             * @example clx1a2b3c0000abcd1234efgh
             */
            surveyId: string;
            /**
             * @description 這份問卷總共有幾份填答
             * @example 30
             */
            responseCount: number;
            /** @description 每一題的摘要，依 order 由小到大 */
            questions: components["schemas"]["QuestionSummaryEntity"][];
        };
        RegisterDto: {
            /**
             * Format: email
             * @description 電子信箱
             * @example someone@example.com
             */
            email: string;
            /**
             * Format: password
             * @description 密碼（bcrypt 的硬上限是 72 字元）
             */
            password: string;
        };
        UserEntity: {
            /**
             * @description 用戶 id（cuid）
             * @example clx1a2b3c0000abcd1234efgh
             */
            id: string;
            /**
             * @description 電子信箱
             * @example someone@example.com
             */
            email: string;
            /**
             * Format: date-time
             * @description 建立時間
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description 最後更新時間
             */
            updatedAt: string;
            /**
             * @description 角色
             * @enum {string}
             */
            role: "USER" | "ADMIN";
        };
        LoginDto: {
            /**
             * Format: email
             * @description 電子信箱
             * @example someone@example.com
             */
            email: string;
            /** @description 密碼 */
            password: string;
        };
        LoginEntity: {
            /**
             * @description JWT 存取權杖
             * @example eyJhbGci.......
             */
            accessToken: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SurveysController_findAll: {
        parameters: {
            query?: {
                /** @description 分頁 */
                page?: number;
                /** @description 每頁筆數 */
                pageSize?: number;
                /** @description 排序 */
                sort?: "createdAt" | "title";
                /** @description 順序 */
                order?: "asc" | "desc";
                /** @description 狀態 */
                status?: "DRAFT" | "PUBLISHED";
                /** @description 搜尋條件 */
                q?: string;
                /** @description 我建立的問卷 */
                mine?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 問卷列表（一頁） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSurveysEntity"];
                };
            };
            /** @description 參數錯誤 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 未登入，或權杖無效／已過期 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
        };
    };
    SurveysController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSurveyDto"];
            };
        };
        responses: {
            /** @description 建立成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SurveyEntity"];
                };
            };
            /** @description 參數錯誤 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 未登入，或權杖無效／已過期 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
        };
    };
    SurveysController_findOne: {
        parameters: {
            query?: {
                /** @description 是否回傳題目 */
                includeQuestions?: boolean;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 單一問卷（?includeQuestions=true 時含題目） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SurveyEntity"];
                };
            };
            /** @description 參數錯誤 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 未登入，或權杖無效／已過期 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 問卷不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
        };
    };
    SurveysController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 刪除前的那一筆問卷 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SurveyEntity"];
                };
            };
            /** @description 未登入，或權杖無效／已過期 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 無此權限 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 問卷不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 問卷已被填寫，無法刪除 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
        };
    };
    SurveysController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSurveyDto"];
            };
        };
        responses: {
            /** @description 更新後的問卷 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SurveyEntity"];
                };
            };
            /** @description 參數錯誤 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 未登入，或權杖無效／已過期 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 無此權限 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 問卷不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
        };
    };
    SurveysController_publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 發布後的問卷 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SurveyEntity"];
                };
            };
            /** @description 未登入，或權杖無效／已過期 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 無此權限 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 問卷不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 問卷沒有任何題目 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
        };
    };
    SurveysController_unpublish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 撤回後的問卷 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SurveyEntity"];
                };
            };
            /** @description 未登入，或權杖無效／已過期 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 無此權限 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 問卷不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 已有人填答 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
        };
    };
    SurveysQuestionsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                surveyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 這份問卷的全部題目，依 order 由小到大 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionEntity"][];
                };
            };
            /** @description 未登入，或權杖無效／已過期 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 問卷不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
        };
    };
    SurveysQuestionsController_replace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                surveyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceQuestionsDto"];
            };
        };
        responses: {
            /** @description 取代後的全部題目，依 order 由小到大 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionEntity"][];
                };
            };
            /** @description 參數錯誤 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 未登入，或權杖無效／已過期 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 無此權限 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 問卷不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 問卷已發布，或已經有人填答 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
        };
    };
    SurveysQuestionsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                surveyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateQuestionDto"];
            };
        };
        responses: {
            /** @description 新增後的題目 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionEntity"];
                };
            };
            /** @description 參數錯誤 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 未登入，或權杖無效／已過期 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 無此權限 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 問卷不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 問卷已發布，無法新增題目 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
        };
    };
    QuestionsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 刪除前的那一題 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionEntity"];
                };
            };
            /** @description 未登入，或權杖無效／已過期 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 無此權限 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 題目不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 問卷已發布，無法刪除 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
        };
    };
    QuestionsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateQuestionDto"];
            };
        };
        responses: {
            /** @description 更新後的題目 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionEntity"];
                };
            };
            /** @description 參數錯誤 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 未登入，或權杖無效／已過期 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 無此權限 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 題目不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 問卷已發布，無法編輯 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
        };
    };
    ResponsesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 單筆作答，含每題的答案與題目內容 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseDetailEntity"];
                };
            };
            /** @description 未登入，或權杖無效／已過期 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 無此權限 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 填寫不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
        };
    };
    SurveyResponsesController_findAll: {
        parameters: {
            query?: {
                /** @description 分頁 */
                page?: number;
                /** @description 每頁筆數 */
                pageSize?: number;
            };
            header?: never;
            path: {
                surveyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 作答列表（一頁，不含 answers） */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponsesEntity"];
                };
            };
            /** @description 參數錯誤 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 未登入，或權杖無效／已過期 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 無此權限 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 問卷不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
        };
    };
    SurveyResponsesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                surveyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateResponseDto"];
            };
        };
        responses: {
            /** @description 送出後的作答（不含 answers） */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEntity"];
                };
            };
            /** @description 請求內容不合法：欄位驗證失敗、題目 ID 重複、題目不屬於這份問卷、沒有答完全部題目、或單選題的答案不在選項裡 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 未登入，或權杖無效／已過期 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 問卷不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 問卷未發布 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
        };
    };
    SurveyResponsesController_summary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                surveyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 每一題的統計，依 order 由小到大 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SurveySummaryEntity"];
                };
            };
            /** @description 未登入，或權杖無效／已過期 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 無此權限 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 問卷不存在 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
        };
    };
    AuthController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            /** @description 註冊成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEntity"];
                };
            };
            /** @description 參數錯誤 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description email已被註冊 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description 登入成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginEntity"];
                };
            };
            /** @description 參數錯誤 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
            /** @description 帳號或密碼錯誤 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
        };
    };
    AuthController_findMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 查詢成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEntity"];
                };
            };
            /** @description 未登入、權杖無效，或該使用者已不存在 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseEntity"];
                };
            };
        };
    };
}
